# Generated by Django 5.0.4 on 2024-05-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_asset', models.CharField(max_length=255)),
                ('full_asset_address', models.TextField()),
                ('address_line1', models.CharField(max_length=255)),
                ('postcode_zip_code', models.CharField(max_length=50)),
                ('town_city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('asset_description', models.TextField(null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('year_built_specific', models.CharField(blank=True, max_length=255, null=True)),
                ('most_recent_major_refurbishment', models.IntegerField(blank=True, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line4', models.CharField(blank=True, max_length=255, null=True)),
                ('county_region', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_ownership_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_tenancy_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_occupier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('breeam_assessment_organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='webapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='webapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='webapp.building')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.question')),
            ],
        ),
    ]
